# GPocoes v1.0 // Plugin em fase de testes, bugs poderao ser encontrados #
# Aproveite o plugin! #
# Coloque o valor que devera ser descontado a cada 3 itens comprados.
Precos:
  Fungo_do_Nether: 350
  Po_De_Blaze: 1000
  Acucar: 1000
  Creme_De_Magma: 1000
  Melancia_Reluzente: 1000
  Lagrima_De_Ghast: 1000
  Pe_De_Coelho: 1000
  Cenoura_Dourada: 1000